import type {
  Budget,
  Category,
  Goal,
  RecurringRule,
  Transaction,
  TransactionTemplate,
  User,
} from "./services/types";

/** Single demo user; aligns with ER `USERS` (no password in client mock). */
export const MOCK_USER_ID = "u_demo_001";

export const mockUser: User = {
  _id: MOCK_USER_ID,
  name: "Priya Sharma",
  email: "priya@example.com",
  currency: "INR",
  timezone: "Asia/Kolkata",
  createdAt: "2024-06-01T00:00:00.000Z",
};

export const mockCategories: Category[] = [
  {
    _id: "cat_salary",
    userId: MOCK_USER_ID,
    name: "Salary",
    icon: "💼",
    color: "#22c55e",
    type: "income",
    isDefault: true,
  },
  {
    _id: "cat_freelance",
    userId: MOCK_USER_ID,
    name: "Freelance",
    icon: "🧑‍💻",
    color: "#4ade80",
    type: "income",
    isDefault: false,
  },
  {
    _id: "cat_groceries",
    userId: MOCK_USER_ID,
    name: "Groceries",
    icon: "🛒",
    color: "#f97316",
    type: "expense",
    isDefault: true,
  },
  {
    _id: "cat_rent",
    userId: MOCK_USER_ID,
    name: "Rent",
    icon: "🏠",
    color: "#a855f7",
    type: "expense",
    isDefault: true,
  },
  {
    _id: "cat_transport",
    userId: MOCK_USER_ID,
    name: "Transport",
    icon: "🚇",
    color: "#3b82f6",
    type: "expense",
    isDefault: false,
  },
  {
    _id: "cat_entertainment",
    userId: MOCK_USER_ID,
    name: "Entertainment",
    icon: "🎬",
    color: "#ec4899",
    type: "expense",
    isDefault: false,
  },
];

export const mockTransactions: Transaction[] = [
  {
    _id: "tx_001",
    userId: MOCK_USER_ID,
    categoryId: "cat_salary",
    recurringId: null,
    type: "income",
    amount: 85000,
    date: "2026-03-01",
    note: "March salary",
    tags: ["payroll"],
    createdAt: "2026-03-01T08:00:00.000Z",
  },
  {
    _id: "tx_002",
    userId: MOCK_USER_ID,
    categoryId: "cat_freelance",
    recurringId: null,
    type: "income",
    amount: 12000,
    date: "2026-03-05",
    note: "UI contract milestone",
    tags: ["client-a"],
    createdAt: "2026-03-05T14:20:00.000Z",
  },
  {
    _id: "tx_003",
    userId: MOCK_USER_ID,
    categoryId: "cat_rent",
    recurringId: "rec_rent",
    type: "expense",
    amount: 22000,
    date: "2026-03-02",
    note: "Apartment rent",
    tags: ["fixed"],
    createdAt: "2026-03-02T09:00:00.000Z",
  },
  {
    _id: "tx_004",
    userId: MOCK_USER_ID,
    categoryId: "cat_groceries",
    recurringId: null,
    type: "expense",
    amount: 4200,
    date: "2026-03-08",
    note: "Weekly vegetables & dairy",
    tags: [],
    createdAt: "2026-03-08T11:30:00.000Z",
  },
  {
    _id: "tx_005",
    userId: MOCK_USER_ID,
    categoryId: "cat_transport",
    recurringId: null,
    type: "expense",
    amount: 1800,
    date: "2026-03-10",
    note: "Metro + cab",
    tags: ["commute"],
    createdAt: "2026-03-10T07:45:00.000Z",
  },
  {
    _id: "tx_006",
    userId: MOCK_USER_ID,
    categoryId: "cat_entertainment",
    recurringId: null,
    type: "expense",
    amount: 950,
    date: "2026-03-12",
    note: "Streaming + book",
    tags: ["leisure"],
    createdAt: "2026-03-12T20:10:00.000Z",
  },
  {
    _id: "tx_007",
    userId: MOCK_USER_ID,
    categoryId: "cat_groceries",
    recurringId: null,
    type: "expense",
    amount: 3100,
    date: "2026-03-18",
    note: "BigBasket order",
    tags: [],
    createdAt: "2026-03-18T16:00:00.000Z",
  },
  {
    _id: "tx_008",
    userId: MOCK_USER_ID,
    categoryId: "cat_transport",
    recurringId: null,
    type: "expense",
    amount: 2400,
    date: "2026-03-22",
    note: "Fuel",
    tags: [],
    createdAt: "2026-03-22T08:00:00.000Z",
  },
];

export const mockBudgets: Budget[] = [
  {
    _id: "bud_001",
    userId: MOCK_USER_ID,
    categoryId: "cat_groceries",
    limitAmount: 8000,
    period: "monthly",
    alertAt: 80,
  },
  {
    _id: "bud_002",
    userId: MOCK_USER_ID,
    categoryId: "cat_transport",
    limitAmount: 5000,
    period: "monthly",
    alertAt: 75,
  },
  {
    _id: "bud_003",
    userId: MOCK_USER_ID,
    categoryId: "cat_entertainment",
    limitAmount: 3000,
    period: "monthly",
    alertAt: 90,
  },
];

export const mockRecurringRules: RecurringRule[] = [
  {
    _id: "rec_rent",
    userId: MOCK_USER_ID,
    categoryId: "cat_rent",
    name: "Rent",
    amount: 22000,
    type: "expense",
    frequency: "monthly",
    nextDueDate: "2026-04-02",
    isActive: true,
  },
  {
    _id: "rec_salary",
    userId: MOCK_USER_ID,
    categoryId: "cat_salary",
    name: "Salary credit",
    amount: 85000,
    type: "income",
    frequency: "monthly",
    nextDueDate: "2026-04-01",
    isActive: true,
  },
];

export const mockTransactionTemplates: TransactionTemplate[] = [
  {
    _id: "tpl_commute",
    userId: MOCK_USER_ID,
    name: "Daily commute",
    categoryId: "cat_transport",
    type: "expense",
    amount: 1800,
    note: "Metro + last mile",
    tags: "commute",
    pinSlot: 0,
  },
  {
    _id: "tpl_lunch",
    userId: MOCK_USER_ID,
    name: "Office lunch",
    categoryId: "cat_groceries",
    type: "expense",
    amount: 350,
    note: "Lunch",
    tags: "",
    pinSlot: 1,
  },
  {
    _id: "tpl_coffee",
    userId: MOCK_USER_ID,
    name: "Coffee",
    categoryId: "cat_entertainment",
    type: "expense",
    amount: 200,
    note: "Cafe",
    tags: "",
    pinSlot: 2,
  },
];

export const mockGoals: Goal[] = [
  {
    _id: "goal_emergency",
    userId: MOCK_USER_ID,
    name: "Emergency fund",
    targetAmount: 200000,
    savedAmount: 118000,
    deadline: "2026-12-31",
    status: "active",
  },
  {
    _id: "goal_trip",
    userId: MOCK_USER_ID,
    name: "Japan trip",
    targetAmount: 150000,
    savedAmount: 42000,
    deadline: "2027-03-15",
    status: "active",
  },
];
